openapi: 3.0.0
info:
  title: Library API
  version: 1.0.0
servers:
- url: /
paths:
  /books:
    get:
      summary: Get all books
      operationId: books_get
      responses:
        "200":
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
    post:
      summary: Add a new book
      operationId: books_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      responses:
        "201":
          description: Book created
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          type: string
      example:
        author: author
        id: 0
        title: title

