openapi: 3.0.0
info:
  title: Library API
  version: 1.0.0
servers:
- url: /
paths:
  /books:
    get:
      operationId: books_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Book"
                type: array
          description: A list of books
      summary: Get all books
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: books_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Book"
        required: true
      responses:
        "201":
          description: Book created
      summary: Add a new book
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    Book:
      example:
        author: author
        id: 0
        title: title
      properties:
        id:
          title: id
          type: integer
        title:
          title: title
          type: string
        author:
          title: author
          type: string
      title: Book
      type: object
